JukeBoxPartyWeb/Controllers/LobbiesController.cs
using JukeBoxPartyWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JukeBoxPartyWeb.Controllers
{
    [Authorize]
    public class LobbiesController : Controller
    {
        // GET: LobbyController
        public ActionResult Index()
        {
            List<Lobby> lobbies = APICaller.GetLobbies().Result;
            for(int i = 0; i < lobbies.Count; i++)
            {
                lobbies[i].IdToShow = i+1; 
            }

            return View(lobbies);
        }

        // GET: LobbyController/Lobby/5
        public ActionResult Lobby(Guid id)
        {
            List<Lobby> lobbies = APICaller.GetLobbies().Result;
            if (lobbies.Find(lobby => lobby.Id == id) != null)
            {
                return View();
            }
            return RedirectToAction("Index");
        }

        // GET: LobbyController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LobbyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LobbyController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LobbyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LobbyController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LobbyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

JukeBoxPartyWeb/Controllers/SongController.cs
using JukeBoxPartyWeb.Models;
using JukeBoxPartyWeb.ReCaptchaV2;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting.Internal;
using System.Data;
using System.IO;

namespace JukeBoxPartyWeb.Controllers
{
    [Authorize(Roles = "Admin, SongManager")]
    public class SongController : Controller
    {
        // GET: SongController
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment;
        public SongController(Microsoft.AspNetCore.Hosting.IHostingEnvironment environment)
        {
            hostingEnvironment = environment;
        }
        public ActionResult Index()
        {
            return View();
        }

        // GET: SongController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SongController/Create
        public async Task<ActionResult> Create()
        {
            var list = await APICaller.GetGenres();

            ViewBag.CategoryList = ToSelectList(list);
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Song model)
        {
            // var result = RedirectToAction("Index", "Home");
            // do other validations on your model as needed
            ViewBag.Message += model.ToString();

            string? captcha = Request.Form["g-Recaptcha-Response"];
            var recaptchaResult = ReCaptchaValidator.IsValid(captcha);
            if (ModelState.IsValid)
            {
                if (recaptchaResult.Success)
                {

                    if (model.Track != null)
                    {
                        var uniqueFileName = GetUniqueFileName(model.Track.FileName);
                        var uploads = Path.Combine(hostingEnvironment.WebRootPath, "media/music");
                        var filePath = Path.Combine(uploads, uniqueFileName);
                        await model.Track.CopyToAsync(new FileStream(filePath, FileMode.Create));
                        model.URL = uniqueFileName;
                        model.Duration *= 1000;
                        try
                        {
                            await APICaller.PostSong(model);
                            ViewBag.Message += string.Format("<b>{0}</b> uploaded.<br />", model.Track.FileName);
                        }
                        catch (HttpRequestException ex)
                        {
                            FileInfo myfileinf = new FileInfo(filePath);
                            if ((System.IO.File.Exists(uniqueFileName)))
                            {
                                System.IO.File.Delete(uniqueFileName);
                            }
                            // ViewBag.Message += ex.Message;
                        }
                    }
                    foreach (var error in recaptchaResult.ErrorCodes)
                    {
                        ModelState.AddModelError(string.Empty, error);
                    }
                }
            }
            var list = await APICaller.GetGenres();
            ViewBag.CategoryList = ToSelectList(list);
            return View(model);
        }
        [NonAction]
        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                      + "_"
                      + Guid.NewGuid().ToString().Substring(0, 4)
                      + Path.GetExtension(fileName);
        }

        // GET: SongController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SongController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SongController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SongController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [NonAction]
        public SelectList ToSelectList(List<Genre> rawList)
        {
            List<SelectListItem> list = new List<SelectListItem>();

            foreach (Genre genre in rawList)
            {
                list.Add(new SelectListItem()
                {
                    Text = genre.Title,
                    Value = genre.Id.ToString()
                });
            }

            return new SelectList(list, "Value", "Text");
        }
    }
}

JukeBoxPartyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JukeBoxParty</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JukeBoxPartyWeb.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="~/media/icon/icon.ico" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JukeBoxParty</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Lobbies" asp-action="Index">Lobbies</a>
                                </li>
                            

                            @if (User.IsInRole("Admin") || User.IsInRole("AccountManager"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Accounts</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin") || User.IsInRole("SongManager"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Song" asp-action="Create">Add song to collection</a>
                                </li>
                            }
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - JukeBoxParty - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>